apiVersion: v1
kind: Pod
metadata:
  name: network-call
  namespace: default
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do ping -c 1 google.com; sleep 5; done
    image: alpine/curl:3.14
    name: network-call
    securityContext:
      appArmorProfile:
        type: Localhost
        localhostProfile: k8s-no-network
    
